build_nginx:
  only:
    - triggers
  script:
    - git clone https://github.com/nginxinc/docker-nginx
    - cd docker-nginx/mainline/alpine
    - sed -i 's/FROM /FROM armhf\//g' Dockerfile
    - TAG=$(sed -n -e 's/ENV NGINX_VERSION //p' Dockerfile)
    - echo ${TAG}
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com/rihardst/cloud_project_infrastructure
    - docker build -t registry.gitlab.com/rihardst/cloud_project_infrastructure:nginx_arm_${TAG} .
    - docker push registry.gitlab.com/rihardst/cloud_project_infrastructure:nginx_arm_${TAG}
    - docker tag registry.gitlab.com/rihardst/cloud_project_infrastructure:nginx_arm_${TAG} registry.gitlab.com/rihardst/cloud_project_infrastructure:nginx_arm_latest
    - docker push registry.gitlab.com/rihardst/cloud_project_infrastructure:nginx_arm_latest

  tags:
    - arm
    - shell

build_postgres:
  only:
    - triggers
  script:
    - git clone https://github.com/docker-library/postgres/
    - cd postgres/9.6/alpine
    - sed -i 's/FROM /FROM armhf\//g' Dockerfile
    - TAG=$(sed -n -e 's/ENV PG_VERSION //p' Dockerfile)
    - echo ${TAG}
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com/rihardst/cloud_project_infrastructure
    - docker build -t registry.gitlab.com/rihardst/cloud_project_infrastructure:postgres_arm_${TAG} .
    - docker push registry.gitlab.com/rihardst/cloud_project_infrastructure:postgres_arm_${TAG}
    - docker tag registry.gitlab.com/rihardst/cloud_project_infrastructure:postgres_arm_${TAG} registry.gitlab.com/rihardst/cloud_project_infrastructure:postgres_arm_latest
    - docker push registry.gitlab.com/rihardst/cloud_project_infrastructure:postgres_arm_latest

  tags:
    - arm
    - shell

build_netdata:
  only:
    - triggers
  script:
    - git clone https://github.com/firehol/netdata
    - cd netdata
    - sed -i 's/FROM /FROM armhf\//g' Dockerfile
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com/rihardst/cloud_project_infrastructure
    - docker build -t registry.gitlab.com/rihardst/cloud_project_infrastructure:netdata_arm_latest .
    - docker push registry.gitlab.com/rihardst/cloud_project_infrastructure:netdata_arm_latest

  tags:
    - arm
    - shell

build_python:
  only:
    - triggers
  script:
    - git clone https://github.com/docker-library/python
    - cd $(ls -d python/*/ | sort | tail -n 1)alpine
    - sed -i 's/FROM /FROM armhf\//g' Dockerfile
    - sed -i 's/\&\& gpg --keyserver/\&\& gpg-agent --daemon \&\& gpg --keyserver/g' Dockerfile
    - TAG=$(sed -n -e 's/ENV PYTHON_VERSION //p' Dockerfile)
    - echo ${TAG}
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com/rihardst/cloud_project_infrastructure
    - docker build -t registry.gitlab.com/rihardst/cloud_project_infrastructure:python_arm_${TAG} .
    - docker push registry.gitlab.com/rihardst/cloud_project_infrastructure:python_arm_${TAG}
    - docker tag registry.gitlab.com/rihardst/cloud_project_infrastructure:python_arm_${TAG} registry.gitlab.com/rihardst/cloud_project_infrastructure:python_arm_latest
    - docker push registry.gitlab.com/rihardst/cloud_project_infrastructure:python_arm_latest

  tags:
    - arm
    - shell

build_python2:
  only:
    - triggers
  script:
    - git clone https://github.com/docker-library/python
    - cd $(ls -d python/2*/ | sort | tail -n 1)alpine
    - sed -i 's/FROM /FROM armhf\//g' Dockerfile
    - sed -i 's/\&\& gpg --keyserver/\&\& gpg-agent --daemon \&\& gpg --keyserver/g' Dockerfile
    - TAG=$(sed -n -e 's/ENV PYTHON_VERSION //p' Dockerfile)
    - echo ${TAG}
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com/rihardst/cloud_project_infrastructure
    - docker build -t registry.gitlab.com/rihardst/cloud_project_infrastructure:python_arm_${TAG} .
    - docker push registry.gitlab.com/rihardst/cloud_project_infrastructure:python_arm_${TAG}
    - docker tag registry.gitlab.com/rihardst/cloud_project_infrastructure:python_arm_${TAG} registry.gitlab.com/rihardst/cloud_project_infrastructure:python_arm_latest2
    - docker push registry.gitlab.com/rihardst/cloud_project_infrastructure:python_arm_latest2

  tags:
    - arm
    - shell

build_vault:
  only:
    - triggers
  script:
    - git clone https://github.com/hashicorp/docker-vault
    - cd $(ls -d docker-vault/*/ | sort | tail -n 1) # Find the latest version
    - mkdir bin
    - wget http://ftp.us.debian.org/debian/pool/main/d/dumb-init/dumb-init_1.2.0-1_armhf.deb
    - ar -x *.deb
    - tar -xvf data.tar.xz
    - cp usr/bin/dumb-init bin/
    - wget  $(curl -s https://api.github.com/repos/tianon/gosu/releases/latest | grep -e '\"browser_download_url.*armhf\"' | sed -n 's/"browser_download_url.* "//p' | sed 's/"//g') -O bin/gosu
    - chmod -R 755 bin/
    - sed -i 's#FROM .*#FROM registry.gitlab.com/rihardst/cloud_project_infrastructure:alpine_armhf_3.6.1#g' Dockerfile
    - sed -i 's/amd64/arm/g' Dockerfile
    - sed -i 's/gpg --recv-keys/gpg-agent --daemon \&\& gpg --keyserver ha.pool.sks-keyservers.net --recv-keys/g' Dockerfile
    - sed -i '/docker-base/ d' Dockerfile
    - sed -i '/cp bin\/gosu/ d' Dockerfile
    - sed -i '/adduser/a ADD bin/ /bin/' Dockerfile
    - TAG=$(sed -n -e 's/ENV VAULT_VERSION=//p' Dockerfile)
    - echo ${TAG}
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com/rihardst/cloud_project_infrastructure
    - docker build -t registry.gitlab.com/rihardst/cloud_project_infrastructure:vault_arm_${TAG} .
    - docker push registry.gitlab.com/rihardst/cloud_project_infrastructure:vault_arm_${TAG}

  tags:
    - arm
    - shell