build_nginx:
  script:
    - git clone https://github.com/nginxinc/docker-nginx
    - cd docker-nginx/mainline/alpine
    - sed -i 's/FROM /FROM armhf\//g' Dockerfile
    - TAG=$(sed -n -e 's/ENV NGINX_VERSION //p' Dockerfile)
    - echo ${TAG}
    - username="gitlab-ci-token"
    - password=$CI_JOB_TOKEN
    - gitlab_host="gitlab.com"
    - repository="rihardst/cloud_project_infrastructure"
    - gitlabreg_host="registry.gitlab.com"
    - headers="Authorization&#58 Basic $(echo -n "${username}:${password}" | base64)"
    - response=$(curl -s -H "$headers" "https://${gitlab_host}/jwt/auth?account=${username}&scope=repository:${repository}:pull&service=container_registry")
    - token=$(echo $response | cut -c10- | sed 's/.$//')
    - curl -H "Authorization&#58 Bearer $token" "https://${gitlabreg_host}/v2/${repository}/tags/list"
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com/rihardst/cloud_project_infrastructure
    - docker build -t registry.gitlab.com/rihardst/cloud_project_infrastructure:nginx_arm_${TAG} .
    - docker push registry.gitlab.com/rihardst/cloud_project_infrastructure:nginx_arm_${TAG}
    - docker tag registry.gitlab.com/rihardst/cloud_project_infrastructure:nginx_arm_${TAG} registry.gitlab.com/rihardst/cloud_project_infrastructure:nginx_arm_latest
    - docker push registry.gitlab.com/rihardst/cloud_project_infrastructure:nginx_arm_latest

  tags:
    - arm
    - shell

build_postgres:
  script:
    - git clone https://github.com/docker-library/postgres/
    - cd postgres/9.6/alpine
    - sed -i 's/FROM /FROM armhf\//g' Dockerfile
    - TAG=$(sed -n -e 's/ENV PG_VERSION //p' Dockerfile)
    - echo ${TAG}
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com/rihardst/cloud_project_infrastructure
    - docker build -t registry.gitlab.com/rihardst/cloud_project_infrastructure:postgres_arm_${TAG} .
    - docker push registry.gitlab.com/rihardst/cloud_project_infrastructure:postgres_arm_${TAG}
    - docker tag registry.gitlab.com/rihardst/cloud_project_infrastructure:postgres_arm_${TAG} registry.gitlab.com/rihardst/cloud_project_infrastructure:postgres_arm_latest
    - docker push registry.gitlab.com/rihardst/cloud_project_infrastructure:postgres_arm_latest

  tags:
    - arm
    - shell