build_nginx:
  only:
    - triggers
  script:
    - git clone https://github.com/nginxinc/docker-nginx
    - cd docker-nginx/mainline/alpine
    - sed -i 's/FROM /FROM armhf\//g' Dockerfile
    - TAG=$(sed -n -e 's/ENV NGINX_VERSION //p' Dockerfile)
    - echo ${TAG}
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com/rihardst/cloud_project_infrastructure
    - docker build -t registry.gitlab.com/rihardst/cloud_project_infrastructure:nginx_arm_${TAG} .
    - docker push registry.gitlab.com/rihardst/cloud_project_infrastructure:nginx_arm_${TAG}
    - docker tag registry.gitlab.com/rihardst/cloud_project_infrastructure:nginx_arm_${TAG} registry.gitlab.com/rihardst/cloud_project_infrastructure:nginx_arm_latest
    - docker push registry.gitlab.com/rihardst/cloud_project_infrastructure:nginx_arm_latest

  tags:
    - arm
    - shell

build_postgres:
  only:
    - triggers
  script:
    - git clone https://github.com/docker-library/postgres/
    - cd postgres/9.6/alpine
    - sed -i 's/FROM /FROM armhf\//g' Dockerfile
    - TAG=$(sed -n -e 's/ENV PG_VERSION //p' Dockerfile)
    - echo ${TAG}
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com/rihardst/cloud_project_infrastructure
    - docker build -t registry.gitlab.com/rihardst/cloud_project_infrastructure:postgres_arm_${TAG} .
    - docker push registry.gitlab.com/rihardst/cloud_project_infrastructure:postgres_arm_${TAG}
    - docker tag registry.gitlab.com/rihardst/cloud_project_infrastructure:postgres_arm_${TAG} registry.gitlab.com/rihardst/cloud_project_infrastructure:postgres_arm_latest
    - docker push registry.gitlab.com/rihardst/cloud_project_infrastructure:postgres_arm_latest

  tags:
    - arm
    - shell

build_netdata:
  only:
    - triggers
  script:
    - git clone https://github.com/firehol/netdata
    - cd netdata
    - sed -i 's/FROM /FROM armhf\//g' Dockerfile
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com/rihardst/cloud_project_infrastructure
    - docker build -t registry.gitlab.com/rihardst/cloud_project_infrastructure:netdata_arm_latest .
    - docker push registry.gitlab.com/rihardst/cloud_project_infrastructure:netdata_arm_latest

  tags:
    - arm
    - shell

build_python:
  only:
    - triggers
  script:
    - git clone https://github.com/docker-library/python
    - cd $(ls -d python/*/ | sort | tail -n 1)alpine
    - sed -i 's/FROM /FROM armhf\//g' Dockerfile
    - sed -i 's/\&\& gpg --keyserver/\&\& gpg-agent --daemon \&\& gpg --keyserver/g' Dockerfile
    - TAG=$(sed -n -e 's/ENV PYTHON_VERSION //p' Dockerfile)
    - echo ${TAG}
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com/rihardst/cloud_project_infrastructure
    - docker build -t registry.gitlab.com/rihardst/cloud_project_infrastructure:python_arm_${TAG} .
    - docker push registry.gitlab.com/rihardst/cloud_project_infrastructure:python_arm_${TAG}
    - docker tag registry.gitlab.com/rihardst/cloud_project_infrastructure:python_arm_${TAG} registry.gitlab.com/rihardst/cloud_project_infrastructure:python_arm_latest
    - docker push registry.gitlab.com/rihardst/cloud_project_infrastructure:python_arm_latest

  tags:
    - arm
    - shell

build_python2:
  only:
    - triggers
  script:
    - git clone https://github.com/docker-library/python
    - cd $(ls -d python/2*/ | sort | tail -n 1)alpine
    - sed -i 's/FROM /FROM armhf\//g' Dockerfile
    - sed -i 's/\&\& gpg --keyserver/\&\& gpg-agent --daemon \&\& gpg --keyserver/g' Dockerfile
    - TAG=$(sed -n -e 's/ENV PYTHON_VERSION //p' Dockerfile)
    - echo ${TAG}
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com/rihardst/cloud_project_infrastructure
    - docker build -t registry.gitlab.com/rihardst/cloud_project_infrastructure:python_arm_${TAG} .
    - docker push registry.gitlab.com/rihardst/cloud_project_infrastructure:python_arm_${TAG}
    - docker tag registry.gitlab.com/rihardst/cloud_project_infrastructure:python_arm_${TAG} registry.gitlab.com/rihardst/cloud_project_infrastructure:python_arm_latest2
    - docker push registry.gitlab.com/rihardst/cloud_project_infrastructure:python_arm_latest2

  tags:
    - arm
    - shell