version: '3'
services:
  nginx:
    image: registry.gitlab.com/rihardst/cloud_project_infrastructure:nginx_arm_latest
    container_name: nginx01
    ports:
      - "80:8001"
      - "443:8000"
    volumes:
      - ./src/:/src/
      - ./config/nginx/:/etc/nginx/conf.d/
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./static/:/static/
      - /var/docker/certbot/etc/archive/:/etc/nginx/ssl/
    depends_on:
      - web
  web:
    build: .
    container_name: django01
    command: sh -c "python manage.py makemigrations && python manage.py migrate && gunicorn blog_project.wsgi -b 0.0.0.0:8000 -b 0.0.0.0:8001"
    depends_on:
      - postgres
    volumes:
      - ./src:/src
      - ./static:/static
    expose:
      - "8000"

  postgres:
    image: registry.gitlab.com/rihardst/cloud_project_infrastructure:postgres_arm_latest
    container_name: postgres01
    volumes:
      - /var/docker/postgresql/data:/var/lib/postgresql/data

  netdata:
    image: registry.gitlab.com/rihardst/cloud_project_infrastructure:netdata_arm_latest
    container_name: netdata01
    hostname: c_netdata
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
    cap_add:
      - SYS_PTRACE
    ports:
      - "19999:19999"