version: '2'
services:
  nginx:
    image: registry.gitlab.com/rihardst/cloud_project_infrastructure:nginx_arm
    container_name: nginx01
    ports:
      - "8000:8000"
    volumes:
      - ./src:/src
      - ./config/nginx:/etc/nginx/conf.d
      - ./static:/static
    depends_on:
      - web
  web:
    build: .
    container_name: django01
    command: bash -c "python manage.py makemigrations && python manage.py migrate && gunicorn blog_project.wsgi -b 0.0.0.0:8000"
    depends_on:
      - db
    volumes:
      - ./src:/src
      - ./static:/static
    expose:
      - "8000"

  db:
    image: registry.gitlab.com/rihardst/cloud_project_infrastructure:postgres_arm
    container_name: postgres01