---
- hosts: all
  remote_user: blogapp
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - tersmitten.fail2ban
    - geerlingguy.security
  vars:
    fail2ban_services:
      - name: sshd
        port: 22
        bantime: 3600
  tasks:
    - name: Set authorized key took from file
      authorized_key:
        user: blogapp
        state: present
        key: "{{ lookup('file', '/home/rihards/.ssh/scaleway.pub') }}"